version: "3"
services:
  tileserver:
    image: maptiler/tileserver-gl:v5.2.0
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - ALLOW_CORS=true
    depends_on:
      - downloader

  downloader:
    build: .
    volumes:
      - ./data:/data
