version: '3'
services:
  tileserver:
    image: maptiler/tileserver-gl:latest
    # or try this alternative image
    # image: klokantech/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - ALLOW_CORS=true 